// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "f8b07525-5cb5-45bd-86e8-08a0e6cc48c7");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 1544172795);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1544172675);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1544173035);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1544172915);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "custom");
user_pref("browser.contentblocking.introCount", 20);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1544172645);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 77);
user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr", false);
user_pref("browser.newtabpage.activity-stream.impressionId", "{3b1873d8-5e59-4ae4-b6bf-f133d3b6e405}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "yandex");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1544104800);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://yandex.com\",\"label\":\"@яндекс\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"webcompat-reporter_mozilla_org\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1544172687228");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1544174484228");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1544173083136");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1544176683136");
user_pref("browser.search.region", "RU");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1544172655");
user_pref("browser.slowStartup.averageTime", 5354);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20181206214149");
user_pref("browser.startup.homepage_override.mstone", "65.0a1");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Яндекс");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 1);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1544172659158");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.iniFile.exists.appversion", "65.0a1");
user_pref("distribution.iniFile.exists.value", false);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "a775f908f99c4ceda57448921bee47f0");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.formautofill.addresses.enabled", false);
user_pref("extensions.formautofill.creditCards.enabled", false);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "65.0a1");
user_pref("extensions.lastPlatformVersion", "65.0a1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"092e0683-d546-44e8-90fc-ca8870fbed1f\",\"screenshots@mozilla.org\":\"aec0e6d0-a88f-4f1f-95a1-dc1354e08641\",\"webcompat-reporter@mozilla.org\":\"ff0e4015-5141-4de5-9b77-3512d519939d\",\"webcompat@mozilla.org\":\"d2c7769e-dda9-4c93-b700-76cfc4d20a19\"}");
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1544172675);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20181206214149");
user_pref("media.gmp-manager.lastCheck", 1544172671);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.cookieBehavior", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("privacy.trackingprotection.enabled", true);
user_pref("security.sandbox.content.tempDirSuffix", "099ed69a-3c41-4b9e-8ed5-eb4a0422b682");
user_pref("security.sandbox.plugin.tempDirSuffix", "417de164-1e42-4174-97cb-bd65c8e7495c");
user_pref("services.blocklist.addons.checked", 1544128982);
user_pref("services.blocklist.gfx.checked", 1544128982);
user_pref("services.blocklist.onecrl.checked", 1544128982);
user_pref("services.blocklist.pinning.checked", 1544128982);
user_pref("services.blocklist.plugins.checked", 1544128982);
user_pref("services.settings.clock_skew_seconds", 43690);
user_pref("services.settings.last_etag", "\"1544128758657\"");
user_pref("services.settings.last_update_seconds", 1544128982);
user_pref("services.settings.main.language-dictionaries.last_check", 1544128982);
user_pref("services.settings.main.onboarding.last_check", 1544128982);
user_pref("services.settings.main.sites-classification.last_check", 1544128982);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.engine.addresses.available", true);
user_pref("services.sync.engine.creditcards.available", true);
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1544172643);
user_pref("toolkit.telemetry.cachedClientID", "e92d6629-442a-4744-944f-b9c80ba54b9e");
user_pref("toolkit.telemetry.previousBuildID", "20181206214149");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("urlclassifier.trackingTable", "test-track-simple,base-track-digest256,content-track-digest256");
