// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1548128244);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.capacity", 1013760);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.search.countryCode", "RU");
user_pref("browser.search.region", "RU");
user_pref("calendar.categories.names", "Бизнес,Встречи,Годовщины,Дни рождения,Доходы,Заказчики,Звонки,Идеи,Избранное,Каникулы,Клиенты,Конкурсы,Личное,Ответы,Отпуск,Подарки,Поставщики,Праздники,Проекты,Путешествия,Разное");
user_pref("calendar.list.sortOrder", "ca58b065-417b-42ca-838a-dabb3e6829b2");
user_pref("calendar.preferences.lightning.selectedTabIndex", 0);
user_pref("calendar.registry.ca58b065-417b-42ca-838a-dabb3e6829b2.calendar-main-default", true);
user_pref("calendar.registry.ca58b065-417b-42ca-838a-dabb3e6829b2.calendar-main-in-composite", true);
user_pref("calendar.registry.ca58b065-417b-42ca-838a-dabb3e6829b2.name", "Мой календарь");
user_pref("calendar.registry.ca58b065-417b-42ca-838a-dabb3e6829b2.type", "storage");
user_pref("calendar.registry.ca58b065-417b-42ca-838a-dabb3e6829b2.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "floating");
user_pref("calendar.ui.version", 3);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installedDistroAddon.{e2fda1a4-762b-4020-b5ad-a41df1933103}", true);
user_pref("extensions.lastAppBuildId", "20181217101353");
user_pref("extensions.lastAppVersion", "64.0");
user_pref("extensions.lastPlatformVersion", "64.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"{e2fda1a4-762b-4020-b5ad-a41df1933103}\":\"99e43658-d50a-4522-aba5-80000a402fa5\"}");
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.preferences.advanced.selectedTabIndex", 0);
user_pref("mail.preferences.compose.selectedTabIndex", 2);
user_pref("mail.preferences.display.selectedTabIndex", 2);
user_pref("mail.rights.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 17);
user_pref("mailnews.database.global.datastore.id", "d288afbb-a2a8-415e-ad6b-e22541a1302");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "64.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Важное");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Рабочее");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Личное");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "К исполнению");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Отложено");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("security.sandbox.plugin.tempDirSuffix", "cd516efc-3484-44c8-b820-eed01cd1d590");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20181129151909");
user_pref("toolkit.telemetry.prompted", 2);
