# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1544149903);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1544150023);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 19);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.search.countryCode", "RU");
user_pref("browser.search.region", "RU");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.slowStartup.averageTime", 3329);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20181115190449");
user_pref("browser.startup.homepage_override.mstone", "4.1.7");
user_pref("browser.taskbar.lastgroupid", "A3665BA0C7D475A");
user_pref("devtools.chrome.enabled", true);
user_pref("devtools.debugger.remote-enabled", true);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:28.2.1");
user_pref("extensions.lastAppVersion", "28.2.1");
user_pref("extensions.lastPlatformVersion", "4.1.7");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"C:\\\\Program Files\\\\Pale Moon\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"28.2.1\",\"st\":1542626304359}}}");
user_pref("gfx.crash-guard.d3d11layers.appVersion", "28.2.1");
user_pref("gfx.crash-guard.d3d11layers.deviceID", "0x0166");
user_pref("gfx.crash-guard.d3d11layers.driverVersion", "10.18.10.4358");
user_pref("gfx.crash-guard.d3d11layers.feature-d2d", true);
user_pref("gfx.crash-guard.d3d11layers.feature-d3d11", true);
user_pref("gfx.crash-guard.status.d3d11layers", 2);
user_pref("gfx.crash-guard.status.d3d11video", 2);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.history.expiration.transient_current_max_pages", 122334);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("sanity-test.device-id", "0x0166");
user_pref("sanity-test.driver-version", "10.18.10.4358");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20181115190449");
user_pref("signon.importedFromSqlite", true);
user_pref("status4evar.firstRun", false);
user_pref("status4evar.migration", 8);
user_pref("toolkit.startup.last_success", 1544149872);
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
