// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.auto-addon-background-update-timer", 1544037402);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1544037372);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.user-agent-updates-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.capacity", 524288);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1544037357478");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1544039174478");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1544037345741");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1544040945741");
user_pref("browser.startup.homepage_override.mstone", "63.0.2");
user_pref("dom.presentation.device.name", "VirtualBox");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.getAddons.cache.lastUpdate", 1544037407);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20181105152108");
user_pref("extensions.lastAppVersion", "63.0.2");
user_pref("extensions.lastPlatformVersion", "63.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"webcompat@mozilla.org\":\"12608c68-1b1f-4c44-8fe6-3af84075baff\"}");
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-manager.buildID", "20181105152108");
user_pref("media.gmp-manager.lastCheck", 1544037403);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("mma.device_id", "cee9811a-6b00-44f3-a9f2-36369a262794");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
