pref("mail.identity.default.request_receipt_header_type", 0);
pref("mail.identity.default.request_return_receipt_on", !1);
pref("mail.identity.default.use_custom_prefs", !1);
pref("mail.server.default.incorporate_return_receipt", 0);
pref("mail.server.default.mdn_not_in_to_cc", 2);
pref("mail.server.default.mdn_other", 2);
pref("mail.server.default.mdn_outside_domain", 2);
pref("mail.server.default.mdn_report_enabled", !0)
pref("mail.server.default.mdn_report_enabled", !0);