name: Adblock Bypass
description: A message asking you to disable your ad blocker
labels: ["data"]

body:
  - type: markdown
    attributes:
      value: |
        ### Basic information
        

  - type: checkboxes
    attributes:
      label: Prerequisites
      description: To avoid invalid reports, please check and confirm following checkboxes.
      options:
        - label: Only one ad blocker is enabled.
          required: true
        - label: [Look](https://github.com/slavasound/test/issues) maybe your issue is already solved.
          required: true
  - type: input
    id: url
    attributes:
      label: Check the link/s
      description: |
      Enter the web address where the issue occurred.
      The backticks (`) surrounding the URLs are important, it prevents the URL from being clickable. 
      placeholder: ex. `https://example.com/`
    validations:
      required: true
  - type: input
    id: ip_address
    attributes:
      label: Reported from
      description: In which country is your IP address?
      placeholder: ex. United States of America, France, Germany or Russia
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ### User environment
  - type: dropdown
    id: browsers
    attributes:
      label: Which browser/s do you use?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Opera
    validations:
      required: true
  - type: dropdown
    id: browsers_type
    attributes:
      label: What type of device are you using the browser on?
      multiple: true
      options:
        - Desktop
        - Mobile
    validations:
      required: true
  - type: dropdown
    id: application
    attributes:
      label: What product do you use?
      multiple: false
      options:
        - AdGuard Browser Extension
        - uBlock Origin Extension
        - AdGuard for Android
        - AdGuard for Mac
        - AdGuard for Windows
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Ad blocker version
      description: Which version of the software are you using?
      placeholder: ex. 1.71.2
    validations:
      required: true

- type: dropdown
    id: filters
    attributes:
      label: What filters do you have enabled?
      description: Select enabled filters from the list or enter URLs of any custom filters in the comment field below.
      multiple: true
      options:
        - EasyList
        - EasyPrivacy
        - AdGuard Base filter
        - AdGuard Mobile Ads filter
        - AdGuard Chinese filter
        - AdGuard Dutch filter
        - AdGuard French filter
        - AdGuard German filter
        - AdGuard Japanese filter
        - AdGuard Russian filter
        - AdGuard Spanish/Portuguese filter
        - AdGuard Turkish filter
        - AdGuard Tracking Protection filter
        - AdGuard Annoyances filter
        - uBlock filters
        - uBlock filters – Badware risks
        - uBlock filters – Privacy
        - uBlock filters – Resource abuse
        - uBlock filters – Unbreak
    validations:
      required: true

