name: Adblock Bypass
description: A message asking you to disable your ad blocker
labels: antiadblock

body:
- type: markdown
  attributes:
    value: |
      ## 👋 Welcome to MCI bug tracker
      If you found any sort of bug, or any thing that might break the game, feel free to create a bug report. If you need more urgent help, check our [Discord](https://discord.gg/ShcuJyzJzj)
      <br /><strong><i>Fields marked with an asterisk (*) are required.</i></strong>
      <br />
